baseURL: "https://joewong00.github.io/ceps/"
languageCode: en-us
title: CE Products Synergy Sdn Bhd

# Enable html in markdown
markup:
  goldmark:
    renderer:
      unsafe: true

params:
  google_analytics_id: ""

  logo:
    mobile: "images/CE-Logo.png"
    mobile_height: "36px"
    mobile_width: "36px"
    desktop: "images/CE-Logo.png"
    desktop_height: "29px"
    desktop_width: "217px"
    alt: "Hugo Hero"